name: Waka Readme

on:
  schedule:
    - cron: '0 4 * * *' # Runs daily at 4:00 AM UTC
  workflow_dispatch: # Allows manual trigger from Actions tab

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: "True"
          SHOW_TIMEZONE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LOC_CHART: "True"
          SHOW_SHORT_INFO: "True"
          COMMIT_MESSAGE: "Automated stats update"
